### ISSUE TITLE
API 获取密匙错误怎么解决

### ISSUE THREAD

**Issue by JHL134** [lllk140/BilibiliLogin#1]
是因为没有获取accessKey and cookie吗？如果是那怎么获取，获取后放在哪里呢？麻烦大佬教教我QAQ

**Comment by lllk140** [comment]
一部分人也出现过，我也不知道啊😔

**Comment by YuSprtc** [comment]
我也出现了这个错误，但是我想通过手动输入accesskey和cookie来实现，可以方便告知一下login_qr.json文件的排版格式吗

**Comment by lllk140** [comment]
> 我也出现了这个错误，但是我想通过手动输入accesskey和cookie来实现，可以方便告知一下login_qr.json文件的排版格式吗

{"cookie": "key1=value1; key2=value2", "accessKey": "xxxxxxxxxx"}
